server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cache
    username: cache_user
    password: cache_pwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000
      #key-prefix: tst
    cache-names: product